name: IGUV Weekly Website Updater

on:
  # ▶ "Run workflow"-Button in GitHub → Actions
  workflow_dispatch: {}
  # ⏰ Wöchentlich: Donnerstag 06:00 Europe/Zurich = 04:00 UTC
  schedule:
    - cron: "0 4 * * 4"

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Zurich
      OPENAI_MODEL: gpt-4o-mini
      WP_CONTAINER_ID: weekly-update-content

      # Repository Secrets (Repo → Settings → Secrets and variables → Actions)
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      WP_BASE: ${{ secrets.WP_BASE }}
      WP_PAGE_ID: ${{ secrets.WP_PAGE_ID }}
      WP_USERNAME: ${{ secrets.WP_USERNAME }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Quick sanity check (Keys/ENV)
        run: |
          echo "Model: ${OPENAI_MODEL}"
          if [ -z "${OPENAI_API_KEY}" ]; then
            echo "❌ OPENAI_API_KEY fehlt. Bitte als Repository Secret setzen."
            exit 1
          fi
          for v in WP_BASE WP_PAGE_ID WP_USERNAME WP_APP_PASSWORD; do
            if [ -z "$(eval echo \$$v)" ]; then
              echo "❌ $v fehlt. Bitte als Repository Secret setzen."
              exit 1
            fi
          done
          echo "✅ ENV ok"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater
        run: |
          echo "Starte Weekly Update ..."
          python updater.py

      - name: Dump diagnostics (on failure)
        if: failure()
        run: |
          echo "=== Python version ==="
          python --version
          echo "=== Files ==="
          ls -la
