name: IGUV Weekly Website Updater (Safe Mode + Rebuild Container)

on:
  workflow_dispatch:
    inputs:
      fast:
        description: "FAST-Modus (nur Kernquellen; schneller, weniger Last)"
        required: false
        default: "true"
  schedule:
    # Donnerstag 06:00 Europe/Zurich = 04:00 UTC
    - cron: "0 4 * * 4"

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Zurich

      # Modell & Limits (passen zum updater.py)
      OPENAI_MODEL: gpt-4o-mini
      HTTP_TIMEOUT_S: "25"
      HTTP_MAX_RETRIES: "2"
      MAX_LINKS_PER_SOURCE: "40"
      MAX_TOTAL_CANDIDATES: "150"
      MAX_ITEMS_PER_SECTION_KI: "5"
      OPENAI_REQUEST_TIMEOUT_S: "60"

      # --- WICHTIG: Container-Strategie ---
      # 'rebuild' = ALLE vorhandenen Container/Marker entfernen und EINEN frischen Block einsetzen.
      # 'replace' = nur Inhalt innerhalb vorhandener ID/Marker ersetzen (fallback).
      CONTAINER_STRATEGY: rebuild
      WP_CONTAINER_ID: weekly-update-content

      # Secrets (Repo → Settings → Secrets and variables → Actions)
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      WP_BASE: ${{ secrets.WP_BASE }}
      WP_PAGE_ID: ${{ secrets.WP_PAGE_ID }}
      WP_USERNAME: ${{ secrets.WP_USERNAME }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Quick sanity check (Keys/ENV)
        run: |
          echo "Model: ${OPENAI_MODEL}"
          if [ -z "${OPENAI_API_KEY}" ]; then
            echo "❌ OPENAI_API_KEY fehlt. Bitte als Repository Secret setzen."
            exit 1
          fi
          for v in WP_BASE WP_PAGE_ID WP_USERNAME WP_APP_PASSWORD; do
            if [ -z "$(eval echo \$$v)" ]; then
              echo "❌ $v fehlt. Bitte als Repository Secret setzen."
              exit 1
            fi
          done
          echo "✅ ENV ok"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater (FAST optional)
        run: |
          echo "Starte Weekly Update ..."
          if [ "${{ github.event.inputs.fast }}" = "true" ]; then
            echo "FAST-Modus aktiv."
            python updater.py --fast
          else
            python updater.py
          fi

      - name: Dump diagnostics (on failure)
        if: failure()
        run: |
          echo "=== Python version ==="
          python --version
          echo "=== Working dir ==="
          pwd
          echo "=== Files ==="
          ls -la
