name: IGUV Weekly Website Updater

on:
  schedule:
    # Donnerstag 06:00 Europe/Zurich
    - cron: '0 6 * * 4'
  workflow_dispatch: {}   # erlaubt "Run workflow" jetzt sofort

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Zurich
      WP_BASE: ${{ secrets.WP_BASE }}
      WP_PAGE_ID: ${{ secrets.WP_PAGE_ID }}
      WP_USERNAME: ${{ secrets.WP_USERNAME }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
      WP_CONTAINER_ID: ${{ secrets.WP_CONTAINER_ID }}
      USER_AGENT: IGUV-Weekly-Updater/2.0 (+https://iguv.ch)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run updater
        run: |
          python updater.py
