name: IGUV Weekly Website Updater

on:
  workflow_dispatch:
  schedule:
    # Donnerstag 06:00 Europe/Zurich = 04:00 UTC
    - cron: "0 4 * * 4"

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Zurich

      # OpenAI
      OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
      USE_OPENAI_WEBSEARCH: "1"
      OPENAI_REQUEST_TIMEOUT_S: "600"

      # WP / Endpoint
      WP_BASE: ${{ secrets.WP_BASE }}
      WP_USERNAME: ${{ secrets.WP_USERNAME }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
      WP_API_TOKEN: ${{ secrets.WP_API_TOKEN }}  # optional

      EVENTS_COUNT: "3"

      # Secret
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai==1.99.9 requests==2.32.4 beautifulsoup4==4.13.4 lxml==6.0.0

      - name: Sanity
        run: |
          echo "Model: $OPENAI_MODEL"
          [ -n "$OPENAI_API_KEY" ] || { echo "OPENAI_API_KEY missing"; exit 1; }
          for v in WP_BASE WP_USERNAME WP_APP_PASSWORD; do
            eval val=\$$v
            [ -n "$val" ] || { echo "$v missing"; exit 1; }
          done
          echo "ENV OK"

      - name: Start Weekly Update
        run: |
          echo "Start Weekly Update..."
          python updater.py

      - name: Diagnostics on failure
        if: failure()
        run: |
          python --version
          pip freeze
