name: IGUV Weekly Website Updater

on:
  schedule:
    # Jeden Donnerstag um 06:00 Uhr Zürich-Zeit
    - cron: "0 4 * * 4"  # UTC = 06:00 Europe/Zurich
  workflow_dispatch: # manueller Start möglich

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run updater.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_MODEL: gpt-4o-mini-search-preview
        WP_BASE: ${{ secrets.WP_BASE }}
        WP_PAGE_ID: ${{ secrets.WP_PAGE_ID }}
        WP_USERNAME: ${{ secrets.WP_USERNAME }}
        WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}
        WP_CONTAINER_ID: weekly-update-content
      run: |
        echo "Starte Weekly Update ..."
        python updater.py

    - name: Debug Logs (bei Fehlern)
      if: failure()
      run: |
        echo "=== Verzeichnisinhalt ==="
        ls -la
        echo "=== Letzte 200 Zeilen Log ==="
        tail -n 200 /home/runner/work/_temp/_runner_file_commands/* || true
