name: IGUV Weekly Website Updater

on:
  workflow_dispatch:
    inputs:
      fast:
        description: "FAST mode (core sources only)"
        required: false
        default: "true"
  schedule:
    # Thursday 06:00 Europe/Zurich = 04:00 UTC
    - cron: "0 4 * * 4"

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      TZ: Europe/Zurich

      # Model & safe-mode limits
      OPENAI_MODEL: gpt-4o-mini
      HTTP_TIMEOUT_S: "25"
      HTTP_MAX_RETRIES: "2"
      MAX_LINKS_PER_SOURCE: "40"
      MAX_TOTAL_CANDIDATES: "150"
      MAX_ITEMS_PER_SECTION_KI: "5"
      OPENAI_REQUEST_TIMEOUT_S: "60"

      # Container handling
      CONTAINER_STRATEGY: rebuild
      WP_CONTAINER_ID: weekly-update-content

      # Secrets
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      WP_BASE: ${{ secrets.WP_BASE }}
      WP_PAGE_ID: ${{ secrets.WP_PAGE_ID }}
      WP_USERNAME: ${{ secrets.WP_USERNAME }}
      WP_APP_PASSWORD: ${{ secrets.WP_APP_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Sanity check
        run: |
          echo "Model=$OPENAI_MODEL"
          [ -n "$OPENAI_API_KEY" ] || { echo "OPENAI_API_KEY missing"; exit 1; }
          for v in WP_BASE WP_PAGE_ID WP_USERNAME WP_APP_PASSWORD; do
            eval val=\$$v
            [ -n "$val" ] || { echo "$v missing"; exit 1; }
          done
          echo "ENV OK"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater
        run: |
          echo "Start Weekly Update..."
          if [ "${{ github.event.inputs.fast }}" = "true" ]; then
            python updater.py --fast
          else
            python updater.py
          fi

      - name: Diagnostics on failure
        if: failure()
        run: |
          python --version
          ls -la
